version:	'3'

services:
    nginx:
        container_name: nginx
        volumes:
          - wpdata:/var/www/wordpress
        build:	./requirements/nginx
        env_file:
          - .env
        ports:
          - 443:443
        networks:
          - docker_network
        restart:	always
        hostname:	nginx
        depends_on:
          - wordpress

    wordpress:
        container_name: wordpress
        build:	./requirements/wordpress
        depends_on:
          - mariadb
        env_file:
          - .env
        ports:
          - 9000:9000
        networks:
          - docker_network
        volumes:
          - wpdata:/var/www/wordpress
        restart:	always
        hostname:	wordpress
        expose:
          - "9000"
      
    mariadb:
        container_name: mariadb
        build:	./requirements/mariadb
        env_file:
          - .env
        ports:
          - 3306:3306
        networks:
          - docker_network
        volumes:
          - dbdata:/var/lib/mysql
        restart:	always
        hostname:	mariadb
        expose:
          - "3306"

networks:
  docker_network:
    driver: bridge

volumes:
    dbdata:
        driver:	local
        driver_opts:
          type:	'none'
          o:		'bind'
          device:	'/home/${USER}/data/mariadb'
    wpdata:
        driver:	local
        driver_opts:
          type:	'none'
          o:		'bind'
          device:	'/home/${USER}/data/wordpress'