-- USE mysql;
-- FLUSH PRIVILEGES;
-- CREATE DATABASE IF NOT EXISTS $MYSQL_DB;
-- CREATE USER '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
-- GRANT ALL PRIVILEGES ON $MYSQL_DB.* TO '$MYSQL_USER';
-- ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
-- FLUSH PRIVILEGES;

--# Create table SQL_DATABASE
CREATE DATABASE IF NOT EXISTS $MYSQL_DB;

--# Create user
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';

--# Give right to User
GRANT ALL PRIVILEGES ON $SQL_DATABASE.* TO '$MYSQL_USER'@'%'
	IDENTIFIED BY '$MYSQL_PASSWORD';

--# Change root password
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';

--# Refresh change
FLUSH PRIVILEGES;